"""Core module for Kage."""

from kage.core.agents.scheduler import DependencyGraph, ParallelAgentGroup, ParallelAgentScheduler
from kage.core.hooks import HookDispatchResult, HookEvent, HookManager, HookRegistration
from kage.core.intent import Intent, IntentResult, classify_intent, needs_ai_classification
from kage.core.memory import (
    CompactionConfig,
    LLMMemorySummarizer,
    MemoryBlock,
    MemoryCompactor,
    MemoryRetriever,
    MemoryStore,
    MemorySummarizer,
    MemoryTimestampRange,
    RuleBasedMemorySummarizer,
    TranscriptSegment,
)
from kage.core.models import (
    AuditEntry,
    Command,
    CommandStatus,
    ExecutionEnvironment,
    Finding,
    Message,
    MessageRole,
    PluginCapability,
    PluginMetadata,
    Scope,
    Session,
    Severity,
    Target,
)
from kage.core.observability import (
    TraceEvent,
    TraceRecorder,
    TraceSeverity,
    export_json,
    export_jsonl,
)
from kage.core.planner import ExecutionPlan, PlanStatus, PlanStep
from kage.core.policy import (
    PolicyAction,
    PolicyContext,
    PolicyDecision,
    PolicyEngine,
    PolicyRegistry,
    PolicyRule,
    PolicySeverity,
)
from kage.core.router import CommandRouter, ExecutorType, RouteResult
from kage.core.tools import (
    ToolExecutionError,
    ToolExecutionOrigin,
    ToolExecutionPlan,
    ToolExecutionResult,
    ToolExecutorBinding,
    ToolExecutorKind,
    ToolPermissionMetadata,
    ToolRegistry,
    ToolRegistryError,
    ToolSchema,
    ToolValidationError,
    ToolValidationResult,
    ToolValidationStrategy,
)
from kage.core.workflows import (
    WorkflowExecutor,
    WorkflowLoader,
    WorkflowRegistry,
    WorkflowTemplate,
    WorkflowTemplateSchema,
    ensure_builtin_workflow_templates,
    register_plugin_workflows,
)

__all__ = [
    "AuditEntry",
    "Command",
    "CommandRouter",
    "CommandStatus",
    "ExecutionEnvironment",
    "ExecutionPlan",
    "ExecutorType",
    "Finding",
    "HookDispatchResult",
    "HookEvent",
    "HookManager",
    "HookRegistration",
    "Intent",
    "IntentResult",
    "LLMMemorySummarizer",
    "MemoryBlock",
    "MemoryCompactor",
    "MemoryRetriever",
    "MemoryStore",
    "MemorySummarizer",
    "MemoryTimestampRange",
    "Message",
    "MessageRole",
    "PlanStatus",
    "PlanStep",
    "ParallelAgentGroup",
    "ParallelAgentScheduler",
    "PluginCapability",
    "PluginMetadata",
    "PolicyAction",
    "PolicyContext",
    "PolicyDecision",
    "PolicyEngine",
    "PolicyRegistry",
    "PolicyRule",
    "PolicySeverity",
    "RouteResult",
    "Scope",
    "Session",
    "Severity",
    "Target",
    "DependencyGraph",
    "TraceEvent",
    "TraceRecorder",
    "TraceSeverity",
    "ToolExecutionError",
    "ToolExecutionOrigin",
    "ToolExecutionPlan",
    "ToolExecutionResult",
    "ToolExecutorBinding",
    "ToolExecutorKind",
    "ToolPermissionMetadata",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolSchema",
    "ToolValidationError",
    "ToolValidationResult",
    "ToolValidationStrategy",
    "WorkflowExecutor",
    "WorkflowLoader",
    "WorkflowRegistry",
    "WorkflowTemplate",
    "WorkflowTemplateSchema",
    "ensure_builtin_workflow_templates",
    "register_plugin_workflows",
    "TranscriptSegment",
    "CompactionConfig",
    "RuleBasedMemorySummarizer",
    "classify_intent",
    "export_json",
    "export_jsonl",
    "needs_ai_classification",
]
